import type { TLead } from '~~/shared/types/Lead'

const now = () => new Date().toISOString()

export const SEED_LEADS: TLead[] = [
  {
    id: 1,
    serialCode: 'RL-0001',
    source: 'Facebook',
    customerName: 'Rahim Uddin',
    phone: '01711-234567',
    area: 'Purbachal',
    propertyTypeMain: 'Land',
    propertyTypeSub: 'Ready',
    block: 'A',
    road: '12',
    budgetRange: '50-60 Lac',
    status: 'Hot',
    assignedSalesman: 'Karim H.',
    followUpDate: '2026-05-08',
    notes: null,
    createdAt: '2026-04-10T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 2,
    serialCode: 'RL-0002',
    source: 'Website',
    customerName: 'Salma Begum',
    phone: '01812-345678',
    area: 'Uttara',
    propertyTypeMain: 'Commercial Plot',
    propertyTypeSub: 'Ongoing',
    block: 'B',
    road: '7',
    budgetRange: '1-1.5 Cr',
    status: 'Warm',
    assignedSalesman: 'Ritu A.',
    followUpDate: '2026-05-10',
    notes: null,
    createdAt: '2026-04-12T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 3,
    serialCode: 'RL-0003',
    source: 'Referral',
    customerName: 'Jahangir Alam',
    phone: '01912-456789',
    area: 'Bashundhara',
    propertyTypeMain: 'Land Share',
    propertyTypeSub: 'Installment',
    block: 'C',
    road: '5',
    budgetRange: '80 Lac',
    status: 'Hot',
    assignedSalesman: 'Karim H.',
    followUpDate: '2026-05-06',
    notes: null,
    createdAt: '2026-04-15T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 4,
    serialCode: 'RL-0004',
    source: 'Phone',
    customerName: 'Nasrin Khatun',
    phone: '01611-567890',
    area: 'Gazipur',
    propertyTypeMain: 'Land',
    propertyTypeSub: 'Ready',
    block: 'D',
    road: '3',
    budgetRange: '30-40 Lac',
    status: 'Cold',
    assignedSalesman: 'Ritu A.',
    followUpDate: '2026-05-15',
    notes: null,
    createdAt: '2026-04-20T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 5,
    serialCode: 'RL-0005',
    source: 'Walk-in',
    customerName: 'Tariqul Islam',
    phone: '01511-678901',
    area: 'Purbachal',
    propertyTypeMain: 'Land',
    propertyTypeSub: 'Ready',
    block: 'E',
    road: '18',
    budgetRange: '1.2-1.5 Cr',
    status: 'Hot',
    assignedSalesman: 'Nabil R.',
    followUpDate: '2026-05-09',
    notes: null,
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 6,
    serialCode: 'RL-0006',
    source: 'Facebook',
    customerName: 'Farhana Akter',
    phone: '01911-789012',
    area: 'Uttara',
    propertyTypeMain: 'Commercial Plot',
    propertyTypeSub: 'Ongoing',
    block: 'F',
    road: '2',
    budgetRange: '2-2.5 Cr',
    status: 'Warm',
    assignedSalesman: 'Nabil R.',
    followUpDate: '2026-05-11',
    notes: null,
    createdAt: '2026-03-25T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 7,
    serialCode: 'RL-0007',
    source: 'Referral',
    customerName: 'Moazzem Hossain',
    phone: '01711-890123',
    area: 'Purbachal',
    propertyTypeMain: 'Land',
    propertyTypeSub: 'Ready',
    block: 'G',
    road: '9',
    budgetRange: '75 Lac',
    status: 'Warm',
    assignedSalesman: 'Karim H.',
    followUpDate: '2026-05-20',
    notes: null,
    createdAt: '2026-03-10T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 8,
    serialCode: 'RL-0008',
    source: 'Website',
    customerName: 'Shirina Parvin',
    phone: '01812-901234',
    area: 'Gazipur',
    propertyTypeMain: 'Land Share',
    propertyTypeSub: 'Installment',
    block: 'H',
    road: '14',
    budgetRange: '40 Lac',
    status: 'Not Interested',
    assignedSalesman: 'Ritu A.',
    followUpDate: '2026-04-30',
    notes: 'Not interested in installment plan',
    createdAt: '2026-03-05T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 9,
    serialCode: 'RL-0009',
    source: 'Phone',
    customerName: 'Aminul Haque',
    phone: '01611-012345',
    area: 'Bashundhara',
    propertyTypeMain: 'Land',
    propertyTypeSub: 'Ready',
    block: 'I',
    road: '6',
    budgetRange: '90 Lac',
    status: 'Hot',
    assignedSalesman: 'Nabil R.',
    followUpDate: '2026-05-13',
    notes: null,
    createdAt: '2026-04-18T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 10,
    serialCode: 'RL-0010',
    source: 'Facebook',
    customerName: 'Dilara Begum',
    phone: '01511-123456',
    area: 'Uttara',
    propertyTypeMain: 'Commercial Plot',
    propertyTypeSub: 'Ongoing',
    block: 'J',
    road: '11',
    budgetRange: '3 Cr',
    status: 'Closed',
    assignedSalesman: 'Karim H.',
    followUpDate: '2026-05-25',
    notes: 'Deal closed',
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: now()
  }
]
