import type { TProperty } from '~~/shared/types/Property'

const now = () => new Date().toISOString()

export const SEED_PROPERTIES: TProperty[] = [
  {
    id: 1,
    serialCode: 'PROP-001',
    title: 'Block A Plot 12',
    project: 'Maxwell Garden City',
    area: 'Purbachal',
    block: 'A',
    road: '12',
    face: 'East',
    katha: 5,
    sqft: 3600,
    currentPrice: 4500000,
    previousPrice: 4200000,
    installment: false,
    status: 'Available',
    purchaseType: 'Contracted for sale',
    manager: 'DGM Hasan',
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 2,
    serialCode: 'PROP-002',
    title: 'Commercial Plot B7',
    project: 'Maxwell Business Park',
    area: 'Uttara',
    block: 'B',
    road: '7',
    face: 'North',
    katha: 10,
    sqft: 7200,
    currentPrice: 12000000,
    previousPrice: null,
    installment: true,
    status: 'Hold',
    purchaseType: 'Power Registration',
    manager: 'AGM Rafiq',
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 3,
    serialCode: 'PROP-003',
    title: 'Block C Plot 05',
    project: 'Maxwell Garden City',
    area: 'Purbachal',
    block: 'C',
    road: '5',
    face: 'West',
    katha: 3,
    sqft: 2160,
    currentPrice: 2800000,
    previousPrice: 2600000,
    installment: true,
    status: 'Available',
    purchaseType: 'Contracted for sale',
    manager: 'DGM Hasan',
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 4,
    serialCode: 'PROP-004',
    title: 'Land Share D3',
    project: 'Maxwell Residency',
    area: 'Bashundhara',
    block: 'D',
    road: '3',
    face: 'South',
    katha: 7,
    sqft: 5040,
    currentPrice: 8500000,
    previousPrice: null,
    installment: false,
    status: 'Sold',
    purchaseType: 'Sab Kobla',
    manager: 'AGM Rafiq',
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 5,
    serialCode: 'PROP-005',
    title: 'Block E Plot 18',
    project: 'Maxwell Garden City',
    area: 'Purbachal',
    block: 'E',
    road: '18',
    face: 'East',
    katha: 4,
    sqft: 2880,
    currentPrice: 3600000,
    previousPrice: 3400000,
    installment: true,
    status: 'Available',
    purchaseType: 'Contracted for sale',
    manager: 'DGM Hasan',
    createdAt: '2026-02-10T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 6,
    serialCode: 'PROP-006',
    title: 'Commercial F2',
    project: 'Maxwell Business Park',
    area: 'Uttara',
    block: 'F',
    road: '2',
    face: 'North',
    katha: 8,
    sqft: 5760,
    currentPrice: 9800000,
    previousPrice: null,
    installment: false,
    status: 'Hold',
    purchaseType: 'Ongoing',
    manager: 'AGM Rafiq',
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 7,
    serialCode: 'PROP-007',
    title: 'Block G Plot 09',
    project: 'Maxwell Residency',
    area: 'Bashundhara',
    block: 'G',
    road: '9',
    face: 'West',
    katha: 6,
    sqft: 4320,
    currentPrice: 7200000,
    previousPrice: 6800000,
    installment: true,
    status: 'Available',
    purchaseType: 'Contracted for sale',
    manager: 'DGM Hasan',
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: now()
  },
  {
    id: 8,
    serialCode: 'PROP-008',
    title: 'Land Share H14',
    project: 'Maxwell Garden City',
    area: 'Purbachal',
    block: 'H',
    road: '14',
    face: 'South',
    katha: 5,
    sqft: 3600,
    currentPrice: 5200000,
    previousPrice: 5000000,
    installment: false,
    status: 'Sold',
    purchaseType: 'Power Registration',
    manager: 'AGM Rafiq',
    createdAt: '2026-03-10T00:00:00.000Z',
    updatedAt: now()
  }
]
