ALTER TABLE `email_jobs`
  MODIFY `status` ENUM('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'SKIPPED') NOT NULL DEFAULT 'PENDING',
  ADD COLUMN `schedule` ENUM('ONCE', 'FREQUENCY') NOT NULL DEFAULT 'ONCE',
  ADD COLUMN `frequencySeconds` INTEGER NULL,
  ADD COLUMN `checkerKey` VARCHAR(191) NULL,
  ADD COLUMN `checkerPayload` JSON NULL,
  ADD COLUMN `lastTriedAt` DATETIME(3) NULL;
